### PR TITLE
fix(kubernetes): sort during reconcile

### LINKED ISSUE #19: Order of objects in `tk diff` not stable?

### PR DESCRIPTION
**Pull request by sh0rez**
Allows stable order in show and diff

Fixes #19

### CODE REVIEW

File: pkg/kubernetes/kubernetes.go [hunk 1]
```diff
@@ -67,6 +80,13 @@ func (k *Kubernetes) Reconcile(raw map[string]interface{}, objectspecs ...string
 		}).([]Manifest)
 	}
 
+	sort.SliceStable(out, func(i int, j int) bool {
+		if out[i].Kind() == out[j].Kind() {
+			return out[i].Name() < out[j].Name()
+		}
+		return out[i].Kind() < out[j].Kind()
```
Comment (tomwilkie) [inline pkg/kubernetes/kubernetes.go]: Super nit picky, but I prefer this pattern:

```go
		if out[i].Kind() != out[j].Kind() {
			return out[i].Kind() < out[j].Kind() 
		}
		return out[i].Name() < out[j].Name()
```

IMO it makes it easier to read, esp when sorting by more that two fields.
