### PR TITLE
fix(jsonnet): EvalJsonnet through Loader interface

### LINKED ISSUE #480: Undefined external variable: tanka.dev/environment
This error occurs on the latest build (works just fine in 0.13.0) when I try to use any of the spec data as per https://tanka.dev/config#jsonnet-access:
```
Error: evaluating jsonnet: RUNTIME ERROR: Undefined external variable: tanka.dev/environment
        <internal>/tk.libsonnet:3:8-43  object <anonymous>
        /home/tanka-test/environments/default/main.jsonnet:7:13-19
        Field "test"
        During manifestation
```
Minimal reproducible example:
environments/default/main.jsonnet
```
local tk = import "tk";
{
  test: {
    apiVersion: 'v1',
    kind: 'Namespace',
    metadata: {
      name: tk.env.spec.namespace
    }
  }
}
```
environments/default/spec.json
```
{
  "apiVersion": "tanka.dev/v1alpha1",
  "kind": "Environment",
  "metadata": {
    "name": "environments/default"
  },
  "spec": {
    "apiServer": "",
    "namespace": "default",
    "resourceDefaults": {},
    "expectVersions": {}
  }
}
```
`tk eval environments/default`, also happens on any other command against it.

### PR DESCRIPTION
**Pull request by Duologic**
To run `tk eval`, we also need to handle `import "tk"` and related. As this behavior is specific to the Loader, it seems to make sense to use the Loader interface for this.

Fixes #480 again. :)

### CODE REVIEW

File: pkg/tanka/load.go [hunk 1]
```diff
@@ -114,6 +124,9 @@ type Loader interface {
 	// List returns metadata of all possible environments at path that can be
 	// loaded
 	List(path string, opts LoaderOpts) ([]*v1alpha1.Environment, error)
+
+	// EvalJsonnet returns the raw evaluated Jsonnet
+	EvalJsonnet(path string, opts LoaderOpts) (interface{}, error)
```
Comment (sh0rez) [inline pkg/tanka/load.go:129]:
```suggestion
	Eval(path string, opts LoaderOpts) (interface{}, error)
```

All other methods of the interface are single verbs and Loaders operate on Jsonnet anyways, so this seems redundant.

File: pkg/tanka/load.go [hunk 2]
```diff
@@ -84,6 +84,16 @@ func List(path string, opts Opts) ([]*v1alpha1.Environment, error) {
 	return loader.List(path, LoaderOpts{opts.JsonnetOpts, opts.Name})
 }
 
+// EvalJsonnet returns the raw evaluated Jsonnet
+func EvalJsonnet(path string, opts Opts) (interface{}, error) {
```
Comment (sh0rez) [inline pkg/tanka/load.go:88]: This is functionally equivalent to `Eval(string, Opts) interface, error`. Let's get rid of this one and have a consistent external API (`Eval`, `Peek`, `Load`, `List`)

**Review by sh0rez — CHANGES_REQUESTED** [review]
Very nice! Small bits but generally LGTM

File: pkg/tanka/load.go (hunk 1 above)
Comment (Duologic) [reply pkg/tanka/load.go:129]: This will conflict with the Eval functions in `pkg/tanka/workflow.go`.

**Review by sh0rez — APPROVED** [review]
so much eval
