### PR TITLE
Don't fail on listing namespaces

### LINKED ISSUE #301: tk diff failing when user doesn't have permission to list namespaces
I'm trying out Tanka with a local OKD (OpenShift) cluster, where I do not have permission to list namespaces, and probably some other cluster-level tasks as well (I don't know if this is a general OKD ~limitation~ feature, or specific to our install). As a result `tk diff` just fails since it tries to list the namespaces first. 

```
) tk --version
tk version v0.10.0-11-g62b18e4

) tk diff environments/default
Error from server (Forbidden): namespaces is forbidden: User "kretzke" cannot list namespaces at the cluster scope: no RBAC policy matched
listing namespaces: exit status 1
```

I _am_ able to get a single namespace, so that suggests a slightly more cumbersome alternative could be getting each namespace individually.

I did a [quick patch to make this a non-fatal error](https://github.com/retzkek/tanka/commit/06f613718e2af986aeb548db89b7c1e86955f50c), but will look to make something more robust to properly address this.

### PR DESCRIPTION
**Pull request by malcolmholmes**
Fixes #301.

If we don't have permission to list namespaces, take a (potentially) slower approach, filter
out the namespaces that are referenced in the resources, and check each of those in turn.

These can then be used to identify whether a diff will break, as before.

### CODE REVIEW

File: pkg/kubernetes/diff.go [hunk 1]
```diff
@@ -22,8 +22,16 @@ Please upgrade kubectl to at least version 1.18.1.`)
 
 	// required for separating
 	namespaces, err := k.ctl.Namespaces()
-	if err != nil {
-		return nil, errors.Wrap(err, "listing namespaces")
+	if err != nil || err == nil {
```
Comment (julienduchesne) [inline pkg/kubernetes/diff.go:25]:
```suggestion
	if err != nil {
```
right?

File: pkg/kubernetes/diff.go [hunk 2]
```diff
@@ -209,3 +217,13 @@ func (m multiDiff) diff() (*string, error) {
 	}
 	return &diff, nil
 }
+
+func findNamespaces(state manifest.List) map[string]bool {
+	namespaces := map[string]bool{}
+	for _, m := range state {
+		if m.Metadata().HasNamespace() {
```
Comment (julienduchesne) [inline pkg/kubernetes/diff.go:224]: `Namespace()` already considers `HasNamespace`. Would it be cleaner to write it like this?
```
if namespace := m.Metadata().Namespace(); namespace != "" {
  namespaces[namespace] = true
}
```

File: pkg/kubernetes/diff.go (hunk 1 above)
Comment (malcolmholmes) [reply pkg/kubernetes/diff.go]: Bah, that was a left-over debugging statement. I wanted to trigger the exception code even when an error didn't actually happen.

File: pkg/kubernetes/diff.go (hunk 2 above)
Comment (malcolmholmes) [reply pkg/kubernetes/diff.go]: yep, reasonable, done.

**Review by julienduchesne — APPROVED** [review]

File: pkg/kubernetes/diff.go [hunk 3]
```diff
@@ -209,3 +217,13 @@ func (m multiDiff) diff() (*string, error) {
 	}
 	return &diff, nil
 }
+
+func findNamespaces(state manifest.List) map[string]bool {
+	namespaces := map[string]bool{}
+	for _, m := range state {
+		if namespace := m.Metadata().Namespace(); namespace != "" {
+			namespaces[m.Metadata().Namespace()] = true
```
Comment (julienduchesne) [inline pkg/kubernetes/diff.go:225]:
```suggestion
			namespaces[namespace] = true
```
you can use namespace here, it's defined in the if

**Review by julienduchesne — APPROVED** [review]

**Comment by malcolmholmes** [comment]
A customer has tried this, and confirmed it works.

File: pkg/kubernetes/diff.go [hunk 4]
```diff
@@ -209,3 +217,13 @@ func (m multiDiff) diff() (*string, error) {
 	}
 	return &diff, nil
 }
+
+func findNamespaces(state manifest.List) map[string]bool {
+	namespaces := map[string]bool{}
+	for _, m := range state {
+		if namespace := m.Metadata().Namespace(); namespace != "" {
```
Comment (sh0rez) [inline pkg/kubernetes/diff.go:224]: We do heavy validation of the resource we operate on here, namespace is guaranteed to be set, so checking it here is technically redundant

File: pkg/kubernetes/diff.go [hunk 5]
```diff
@@ -209,3 +217,13 @@ func (m multiDiff) diff() (*string, error) {
 	}
 	return &diff, nil
 }
+
+func findNamespaces(state manifest.List) map[string]bool {
```
Comment (sh0rez) [inline pkg/kubernetes/diff.go:221]: This behavior is generally useful enough to put it onto `manifest.List` directly, maybe like so?

```
func (l manifest.List) Namespaces() []string

File: pkg/kubernetes/diff.go [hunk 6]
```diff
@@ -23,7 +23,15 @@ Please upgrade kubectl to at least version 1.18.1.`)
 	// required for separating
 	namespaces, err := k.ctl.Namespaces()
 	if err != nil {
-		return nil, errors.Wrap(err, "listing namespaces")
+		resourceNamespaces := findNamespaces(state)
+		namespaces = map[string]bool{}
```
Comment (sh0rez) [inline pkg/kubernetes/diff.go:27]:
```suggestion
		namespaces = map[string]struct{}{}
```

File: pkg/kubernetes/diff.go [hunk 7]
```diff
@@ -23,7 +23,15 @@ Please upgrade kubectl to at least version 1.18.1.`)
...
+		for namespace := range resourceNamespaces {
+			_, err = k.ctl.Namespace(namespace)
+			if err != nil {
+				return nil, errors.Wrap(err, "retrieving namespaces")
```
Comment (sh0rez) [inline pkg/kubernetes/diff.go:31]: This misses the case where a namespaces does not exist on the server, which is non-fatal but should just result in the ns not being added to the list, so the following code can handle accordingly

File: pkg/kubernetes/diff.go [hunk 8]
```diff
@@ -23,7 +23,15 @@ Please upgrade kubectl to at least version 1.18.1.`)
 	// required for separating
 	namespaces, err := k.ctl.Namespaces()
 	if err != nil {
```
Comment (sh0rez) [inline pkg/kubernetes/diff.go:25]: This would also make the fallback code run on legit errors (server connection failed, etc)

**Review by sh0rez — CHANGES_REQUESTED** [review]

File: pkg/kubernetes/diff.go (hunk 4 above)
Comment (malcolmholmes) [reply pkg/kubernetes/diff.go:224]: guaranteed? What about cluster-wide resources?

File: pkg/kubernetes/diff.go (hunk 5 above)
Comment (malcolmholmes) [reply pkg/kubernetes/diff.go:221]: sure!

File: pkg/kubernetes/diff.go (hunk 6 above)
Comment (malcolmholmes) [reply pkg/kubernetes/diff.go:27]: makes sense

File: pkg/kubernetes/diff.go (hunk 4 above)
Comment (sh0rez) [reply pkg/kubernetes/diff.go:224]: good point, I did not think of this

File: pkg/kubernetes/diff.go [hunk 9]
```diff
@@ -209,3 +217,13 @@ func (m multiDiff) diff() (*string, error) {
 	}
 	return &diff, nil
 }
+
+func findNamespaces(state manifest.List) map[string]bool {
+	namespaces := map[string]bool{}
```
[the remark this answers is not in the document]
Comment (malcolmholmes) [reply pkg/kubernetes/diff.go:222]: `k.ctl.Namespaces()` already returns a `map[string]bool`. Should we fix that too?

File: pkg/kubernetes/diff.go (hunk 7 above)
Comment (malcolmholmes) [reply pkg/kubernetes/diff.go:34]: Added `--ignore-not-found` so `kubectl` now doesn't report an error on namespace not found. This makes it much easier to catch the condition we are after.

File: pkg/kubernetes/diff.go (hunk 8 above)
Comment (malcolmholmes) [reply pkg/kubernetes/diff.go:25]: In this case, I'm not actually fussed. If there is a problem with the api server, we move on to the next check, and that will fail and report. The user will still get an API server error reported.

File: pkg/kubernetes/diff.go (hunk 5 above)
Comment (malcolmholmes) [reply pkg/kubernetes/diff.go]: done

**Review by Duologic — APPROVED** [review]

File: pkg/kubernetes/diff.go (hunk 9 above)
[the remark this answers is not in the document]
Comment (malcolmholmes) [reply pkg/kubernetes/diff.go]: I left that alone, can fix on another occasion.

File: pkg/kubernetes/diff.go [hunk 10]
```diff
@@ -23,7 +23,18 @@ Please upgrade kubectl to at least version 1.18.1.`)
 	// required for separating
 	namespaces, err := k.ctl.Namespaces()
 	if err != nil {
-		return nil, errors.Wrap(err, "listing namespaces")
+		resourceNamespaces := state.Namespaces()
+		namespaces = map[string]bool{}
+		for _, namespace := range resourceNamespaces {
+			_, err = k.ctl.Namespace(namespace)
+			if err != nil {
+				if errors.Is(err, client.ErrNamespaceNotFound{}) {
```
Comment (sh0rez) [inline pkg/kubernetes/diff.go:31]: Use errors.As for typed errors instead

File: pkg/kubernetes/client/kubectl.go [hunk 11]
```diff
@@ -76,6 +77,34 @@ func (k Kubectl) Namespaces() (map[string]bool, error) {
 	return namespaces, nil
 }
 
+type ErrNamespaceNotFound struct{}
+
+func (e ErrNamespaceNotFound) Error() string {
+	return "Namespace not found"
```
Comment (sh0rez) [inline pkg/kubernetes/client/kubectl.go:83]: Being a struct anyways, it should include the name of the offending namespace

**Review by sh0rez — APPROVED** [review]

File: pkg/kubernetes/diff.go (hunk 10 above)
Comment (malcolmholmes) [reply pkg/kubernetes/diff.go]: fair. Done

File: pkg/kubernetes/client/kubectl.go (hunk 11 above)
Comment (malcolmholmes) [reply pkg/kubernetes/client/kubectl.go]: So we only detect the error type then swallow it - we don't actually report it. But, for potential future use-cases, this is worth doing.
